@startuml
actor Cliente
boundary ApuestasResource
participant PartidoSchema
participant ApuestaSchema
participant PartidoModel
participant ApuestaModel
database data
Cliente -> ApuestasResource: get all 
ApuestasResource -> PartidoModel: get all partidos finalizado=False
PartidoModel -> data: select all
PartidoModel <- data: registros partidos finalizados
PartidoModel -> PartidoSchema: dump many=True
PartidoSchema -> ApuestasResource: collecion en json
ApuestasResource -> Cliente

Cliente -> ApuestasResource: post
ApuestasResource -> ApuestaModel: Guardar apuesta
ApuestaModel -> data: Insert
data -> ApuestaModel: Object
ApuestaModel -> ApuestaSchema: Dump Object
ApuestaSchema -> ApuestasResource: Json
ApuestasResource -> Cliente




@enduml